### PR TITLE
Fix #173: Fix version names in documentation of 1.4.x

### LINKED ISSUE #173: Fix version names in documentation of 1.4.x

### PR DESCRIPTION
**Pull request by jandusil**
Leave the docs same as in 1.5.x, just change the naming to 1.4.x. The agreement with the customer is that the funcionlities stay the same as in 1.5.x

### CODE REVIEW

**Review by romanstrobl — APPROVED** [review]
Looks OK.

**Review by banterCZ — CHANGES_REQUESTED** [review]
We must not change the exiting scripts.

**Review by zcgandcomp — COMMENTED** [review]
Ok if retrospective introduce 1.4.x (as we have to) and introduce the migration guide 1.1.x -> 1.4.0 . This will affect 1.5x as well - imagine somebody who will migrate to 1.4.0 and then he wants to move to 1.5.0.
I would at least modify 1.5.0 and explicitly say that for 1.4.0 -> 1.5.0 no DB migration is required. 
I know this should be clear as we are saying this is for 1.1.x -> 1.5.0 but just in case put there explicit warning.

**Comment by jandusil** [comment]
Okay, so the way I understand this is we can allow retrospective changes as long as we will update the 1.5.0 migration.
Here is the PR for that https://github.com/wultra/mobile-utility-server/pull/181

**Review by banterCZ — APPROVED** [review]
Thanks, my latest comment is reflected and the liquibase scripts are not modified anymore.

**Pull request merged**
